In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30,40,50,60,70,80,90,100]) #1d arr
for array in arr:
    print(array)
print("5th element is " + str(arr[4]))
print(arr.shape)
print(arr.dtype)
arr[5]=45
print("6th element is " + str(arr[5]))

10
20
30
40
50
60
70
80
90
100
5th element is 50
(10,)
int64
6th element is 45


In [3]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])#2d array
for row in arr1:
    print(row)
print(arr1.dtype)
print(arr1.shape)

[1 2 3]
[4 5 6]
int64
(2, 3)


#**array creation**

In [4]:
#coversion from other python structures

listarr=np.array([[1,2,3],[4,5,6],[7,8,9]]) #passed 3 list in array functions = 3d array
print(listarr)
print("-----------------")
dictarr=np.array([{1,2,3},{4,5,6},{7,8,9}]) #passed 3 dictionary in array
print(dictarr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----------------
[{1, 2, 3} {4, 5, 6} {8, 9, 7}]


In [5]:
#creation using zeros and ones
zeros1d=np.zeros(2)
zeros2d=np.zeros((2,4))
print("1d " + str(zeros1d))
print("2d " + str(zeros2d))

#creation usinng arrange function
rng=np.arange(1,11) #(start, end-1)
print("through arrange funtion "+ str(rng))



1d [0. 0.]
2d [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
through arrange funtion [ 1  2  3  4  5  6  7  8  9 10]


In [6]:
#reshaping of array
newarr=np.arange(99)
print(newarr)
reshaped= newarr.reshape(3,33)
print(reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]
